export const actionTypes = {
  setUserPassword: "SET_USER_PASSWORD",
  setUserEmail: "SET_USER_EMAIL",
  setIsUserAccountCreated: "SET_IS_USER_ACCOUNT_CREATED",
  setCurrentUser: "SET_CURENT_USER",
  addNewTask: "ADD_NEW_TASK",
  deleteTasks: "DELETE_TASKS",
  setDeleteAlertOpen: "SET_DELETE_ALERT_OPEN",
  setDeleteAlertClose: "SET_DELETE_ALERT_CLOSE",
  deleteSingleTask: "DELETE_SINGLE_TASK",
  editTask: "EDIT_TASK",
  saveTask: "SAVE_TASK",
  setEditTaskName: "SET_EDIT_TASK_NAME",
  sortTasksByDate: "SORT_TASKS_BY_DATE",
  sortTasksByName: "SORT_TASKS_BY_NAME",
  sortTasksByPiority: "SORT_TASKS_BY_PIORITY",
  openBudgetModalAndSelectWallet: "OPEN_BUDGET_MODAL_AND_SELECT_WALLET",
  closeBudgetModal: "CLOSE_BUDGET_MODAL",
};
